# Generated by Django 5.1.15 on 2026-05-06 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID tâche')),
                ('job_type', models.CharField(choices=[('forecast', 'Prévision'), ('optimize', 'Optimisation'), ('spc', 'Contrôle SPC'), ('generate', 'Génération données'), ('abc', 'Analyse ABC-XYZ')], max_length=20, verbose_name='Type')),
                ('sku_id', models.CharField(blank=True, max_length=20, verbose_name='SKU')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=10, verbose_name='Statut')),
                ('result_json', models.TextField(blank=True, null=True, verbose_name='Résultat JSON')),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche ML',
                'verbose_name_plural': 'Tâches ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('alert_threshold', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte stock")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=10, verbose_name='Statut')),
                ('ml_sku_id', models.CharField(blank=True, help_text='Identifiant dans le catalogue ML synthétique (ex: COMP-001)', max_length=20, verbose_name='SKU ML associé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SKUMLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='SKU ID')),
                ('best_forecast_model', models.CharField(blank=True, max_length=20, verbose_name='Meilleur modèle')),
                ('forecast_mase', models.FloatField(blank=True, null=True, verbose_name='MASE')),
                ('forecast_coverage', models.FloatField(blank=True, null=True, verbose_name='Coverage rate IC')),
                ('reorder_point', models.FloatField(blank=True, null=True, verbose_name='Point de commande')),
                ('order_quantity', models.FloatField(blank=True, null=True, verbose_name='Quantité commandée')),
                ('safety_stock', models.FloatField(blank=True, null=True, verbose_name='Stock de sécurité')),
                ('service_level', models.FloatField(blank=True, null=True, verbose_name='Taux de service')),
                ('capital_reduction', models.FloatField(blank=True, null=True, verbose_name='Réduction capital (%)')),
                ('spc_status', models.CharField(blank=True, max_length=20, verbose_name='Statut SPC')),
                ('spc_n_critical', models.IntegerField(default=0, verbose_name='Signaux critiques')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_forecast_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_profiles', to='inventory.mljobresult')),
                ('last_optimize_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimize_profiles', to='inventory.mljobresult')),
                ('last_spc_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spc_profiles', to='inventory.mljobresult')),
            ],
            options={
                'verbose_name': 'Profil ML SKU',
                'ordering': ['sku_id'],
            },
        ),
    ]
